# Generated by Django 4.0.1 on 2022-01-11 20:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=40)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_profil/')),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
                ('prenom', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_postale', models.CharField(blank=True, max_length=40, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('ville', models.CharField(blank=True, max_length=40, null=True)),
                ('tel_fix', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_mob', models.CharField(blank=True, max_length=10, null=True)),
                ('date_anniv', models.CharField(blank=True, max_length=10, null=True)),
                ('num_secu', models.CharField(blank=True, max_length=13, null=True)),
                ('max_enfants', models.IntegerField(blank=True, null=True)),
                ('num_agrement', models.CharField(blank=True, max_length=6, null=True)),
                ('date_agrement', models.CharField(blank=True, max_length=10, null=True)),
                ('ass_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('ass_auto', models.CharField(blank=True, max_length=20, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
