# Generated by Django 4.0.1 on 2022-01-12 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_profil/')),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
                ('prenom', models.CharField(blank=True, max_length=20, null=True)),
                ('date_anniv', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_profil/')),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
                ('prenom', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_postale', models.CharField(blank=True, max_length=40, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('ville', models.CharField(blank=True, max_length=40, null=True)),
                ('tel_fix', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_mob', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_doc', models.CharField(blank=True, max_length=10, null=True)),
                ('date_anniv', models.CharField(blank=True, max_length=10, null=True)),
                ('num_urssaf', models.CharField(blank=True, max_length=13, null=True)),
                ('ass_mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employeur',
                'verbose_name_plural': 'Employeurs',
            },
        ),
        migrations.CreateModel(
            name='ContactUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
                ('prenom', models.CharField(blank=True, max_length=20, null=True)),
                ('filiation', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_fix', models.CharField(blank=True, max_length=10, null=True)),
                ('tel_mob', models.CharField(blank=True, max_length=10, null=True)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famille.employeur')),
            ],
            options={
                'verbose_name': 'Contact Urgence',
                'verbose_name_plural': 'Contacts Urgences',
            },
        ),
    ]
