# Generated by Django 4.0.1 on 2022-01-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('famille', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enfant',
        ),
    ]
