# Generated by Django 4.0.1 on 2022-01-12 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('famille', '0002_delete_enfant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongePaye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintient_salaire', models.FloatField(blank=True, null=True)),
                ('dix_pourcent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Congé Payé',
                'verbose_name_plural': 'Congés Payés',
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('heure_hebdo', models.IntegerField(blank=True, null=True)),
                ('jour_hebdo', models.IntegerField(blank=True, null=True)),
                ('nb_semaine', models.IntegerField(blank=True, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famille.employeur')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.CreateModel(
            name='TypeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(choices=[('cdi', 'Cdi'), ('cdd', 'Cdd'), ('occasionnel', 'Occasionnel')], max_length=50)),
            ],
            options={
                'verbose_name': 'Titre',
                'verbose_name_plural': 'Titres',
            },
        ),
        migrations.CreateModel(
            name='Remuneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_mensuel', models.FloatField(blank=True, null=True)),
                ('heure_mensuel', models.FloatField(blank=True, null=True)),
                ('taux_h_brut', models.FloatField(blank=True, null=True)),
                ('taux_h_net', models.FloatField(blank=True, null=True)),
                ('jour_mensuel', models.FloatField(blank=True, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrat.contrat')),
            ],
            options={
                'verbose_name': 'Remuneration',
                'verbose_name_plural': 'Remunerations',
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_profil/')),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
                ('prenom', models.CharField(blank=True, max_length=20, null=True)),
                ('date_anniv', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrat.contrat')),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='type_contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrat.typecontrat'),
        ),
    ]
