# Generated by Django 4.0.1 on 2022-01-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='date_anniv',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
